import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/context/Index'
import Navbar from '@/components/Navbar'
import { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
        <Toaster />
          <Navbar />
          <main className='flex min-h-[calc(100vh-5rem)] flex-col mt-[75px]'>
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  )
}
